#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

join () {
  IFS=$1; shift; echo "$*"
}

APP=$1
URLS=$(join ',' $(get_app_urls urls ${APP}))

"$(dirname $0)"/trigger post-deploy ${APP} urls=${URLS}
