#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP=$1

"$(dirname $0)"/trigger post-deploy ${APP} url=$(get_app_urls url ${APP})
